networks:
  piwigo-network:
    external: false

services:
  piwigo:
    build: .
    # image: docker.io/library/rushlana/piwigo-test:latest
    networks:
      - piwigo-network
    ports:
      # Defined in .env
      - '${piwigo_port}:9000'
    depends_on:
      - piwigo-db
    volumes:
      - ./piwigo-data/piwigo:/var/www/html/
      - ./piwigo-data/scripts:/usr/local/bin/scripts/
  piwigo-db:
    image: docker.io/library/mariadb:lts
    restart: always
    environment:
      - MARIADB_RANDOM_ROOT_PASSWORD=true
      # Defined in .env
      - MARIADB_USER=${db_user}
      - MARIADB_PASSWORD=${db_user_password}
      - MARIADB_DATABASE=${db_name}
    networks:
      - piwigo-network
    volumes:
      - ./piwigo-data/mysql:/var/lib/mysql